sim/permission/urls.py
from django.urls import re_path
from .views import *

urlpatterns = [
    re_path(r'^permission_groups/$', CreatePermissionGroupView.as_view(), name='create_permission_group'),
    re_path(r'^group_detail/group=(?P<id>[0-9]{1,100})/$', GroupDetailView.as_view(), name='group_detail'),

    re_path(r'^group_detail_functions/$', GroupDetailFunctions.as_view(), name='group_detail_functions'),
]

sim/sim/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static, settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_auth.urls')),
    re_path(r'^permissions/', include('permission.urls')),
    re_path(r'^xml_editor/', include('xml_editor.urls')),
    re_path(r'^ari_controller/', include('ari_controller.urls'))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sim/permission/models.py
from django.db import models
from django.apps import apps
from django.contrib.auth.models import User

# Create your models here.
class ModelPermission(models.Model):
    model_name = models.CharField(max_length=128, blank=False, null=True, default=None, verbose_name='model name')
    permission_name = models.CharField(max_length=128, blank=False, null=True, default=None, verbose_name='permission name')
    description = models.CharField(max_length=256, blank=False, null=True, default=None, verbose_name='description')
    tag = models.CharField(max_length=1, blank=False, null=True, default=None, verbose_name='tag')
    created_at = models.DateTimeField(auto_now_add=True, blank=True, verbose_name='created at', editable=False)
    updated_at = models.DateTimeField(auto_now=True, blank=True, verbose_name='updated at', editable=False)

    def __str__(self):
        return '{description} (model_name: {model_name}, id: {id}, permission_name: {permission_name})'.format(description=self.description, model_name=self.model_name.upper(), id=self.id, permission_name=self.permission_name)

    class Meta:
        db_table = 'model_permissions'

class PermissionGroup(models.Model):
    model_permissions = models.ManyToManyField(ModelPermission, verbose_name='model permissions')
    name = models.CharField(max_length=16, unique=True, blank=False, default=None, verbose_name='name')
    permissions = models.CharField(max_length=512, blank=True, null=True, default=None, verbose_name='permissions', editable=False)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, verbose_name='created at', editable=False)
    updated_at = models.DateTimeField(auto_now=True, blank=True, verbose_name='updated at', editable=False)

    class Meta:
        db_table = 'permission_groups'

    def __str__(self):
        return self.name

sim/permission/forms.py
from django.forms import ModelForm, Form, CheckboxSelectMultiple, TextInput
from permission.models import PermissionGroup
from django.core import validators
from django.core.exceptions import ValidationError

class UniqueGroupValidator:
    def __init__(self, name, message=None, code=None):
        self.message = message
        self.code = code
        self.name = name

    def __call__(self):
        if self.message is None:
            self.message = u'Grupa z taka nazwa juz istnieje'
        try:
            PermissionGroup.objects.get(name=self.name)
            raise ValidationError(self.message)
        except PermissionGroup.DoesNotExist:
            pass

class CreatePermissionGroupForm(ModelForm):
    class Meta:
        model = PermissionGroup
        fields = ['model_permissions', 'name']
        widgets = {
            'name': TextInput(attrs={'class':'form-control'}),
            'model_permissions': CheckboxSelectMultiple(attrs={'class':'permission_models'}),
        }

    def __init__(self, *args, **kwargs):
        super(CreatePermissionGroupForm, self).__init__(*args, **kwargs)
        max_length_template = u'Maksymalna dlugosc nie powinna byc dluzsza za {limit_value}'
        min_length_template = u'Minimalna dlugosc nie powinna byc mniejsza za {limit_value}'
        self.fields.get('name').min_length = 4
        self.fields.get('name').validators.append(validators.MinLengthValidator(self.fields.get('name').min_length, message=min_length_template.format(limit_value=self.fields.get('name').min_length)))
        self.fields.get('name').error_messages = {'required':'To pole jest wymagane', 'max_length':max_length_template.format(limit_value=self.fields.get('name').max_length), 'unique':u'Grupa z taka nazwa juz istnieje'}
        self.fields.get('model_permissions').error_messages = {'required':'To pole jest wymagane'}

class SearchUsername(Form):
    from user_auth.forms import UserRegistrationForm
    username = UserRegistrationForm().fields.get('username')

sim/permission/views.py
from django.shortcuts import render, redirect, reverse
from permission.check_permission import Permission as UserCheckPermission
from permission.forms import CreatePermissionGroupForm
from django.views.generic import TemplateView, DetailView
from django.http import JsonResponse, HttpResponse
import json
from permission.models import PermissionGroup, ModelPermission
from user_auth.models import UserProfile
from user_auth.views import MainInfo
from django.db.models import Q
from django.forms import BaseForm
from django.contrib.auth.models import User

# Create your views here.

class PermissionGroupMain(MainInfo):
    template_name = 'permissions/permission_group.html'
    model_name = 'permissiongroup'

    def get_context_data(self, **kwargs):
        context = super(PermissionGroupMain, self).get_context_data(**kwargs)
        context['createPermissionGroup_permission'] = UserCheckPermission(self.request, 'permissiongroup', tag='C').__call__()
        context['updatePermissionGroup_permission'] = UserCheckPermission(self.request, 'permissiongroup', tag='U').__call__()
        context['deletePermissionGroup_permission'] = UserCheckPermission(self.request, 'permissiongroup', tag='D').__call__()
        context['viewPermissionGroup_permission'] = UserCheckPermission(self.request, 'permissiongroup', tag='V').__call__()
        context['createPermissionGroupForm'] = CreatePermissionGroupForm
        context['activeGroups'] = PermissionGroup.objects.all()
        return context

class CreatePermissionGroupView(PermissionGroupMain):
    template_name = 'permissions/permission_group.html'

    def post(self, *args, **kwargs):
        if self.request.is_ajax():
            form = CreatePermissionGroupForm({'name':self.request.POST.get('name'), 'model_permissions':json.loads(self.request.POST.get('permissions'))})
            if form.errors:
                errors_list = []
                for error in form.errors:
                    error_dict = {'field_name':error, 'message':form.errors.get(error)[0]}
                    errors_list.append(error_dict)
                return JsonResponse({'success':False, 'errors':errors_list})
            else:
                created_group = PermissionGroup.objects.create(name=form.cleaned_data.get('name'))
                created_group.model_permissions.set(form.cleaned_data.get('model_permissions'))
                print(created_group.name, created_group.id)
            return JsonResponse({'success':True})
        else:
            return redirect(reverse('create_permission_group'))

    def get(self, *args, **kwargs):
        user_permission = UserCheckPermission(self.request, self.model_name).__call__()
        if user_permission:
            return super(CreatePermissionGroupView, self).get(*args, **kwargs)
        else:
            return HttpResponse('permission denied')

    def get_context_data(self, **kwargs):
        context = super(CreatePermissionGroupView, self).get_context_data(**kwargs)
        return context

class GroupDetailView(DetailView, PermissionGroupMain):
    template_name = 'permissions/group_detail.html'
    slug_field = 'id'
    pk_url_kwarg = 'id'
    model = PermissionGroup
    context_object_name = 'group'

    def get_context_data(self, **kwargs):
        self.object = self.get_object()
        context = super(GroupDetailView, self).get_context_data(**kwargs)
        context['users'] = UserProfile.objects.filter(permission_group=self.object)
        context['model_permissions'] = self.object.model_permissions.all()
        return context

    def get(self, *args, **kwargs):
        if UserCheckPermission(self.request, self.model_name, tag='U').__call__() or UserCheckPermission(self.request, self.model_name, tag='C').__call__() or UserCheckPermission(self.request, self.model_name, tag='D').__call__():
            return super(GroupDetailView, self).get(*args, **kwargs)
        else:
            return HttpResponse('permission denied')

class GroupDetailFunctions(TemplateView):
    template_name = 'permissions/group_detail.html'

    def post(self, *args, **kwargs):
        if self.request.is_ajax():
            request_dict = self.request.POST
            if request_dict.get('function') == 'add_permission_to_group':
                permissions_to_show = ModelPermission.objects.exclude(Q(id__in=[permission.id for permission in PermissionGroup.objects.get(id=int(request_dict.get('group_id'))).model_permissions.all()]))
                form = CreatePermissionGroupForm()
                form.fields.get('model_permissions').queryset = permissions_to_show
                form.fields.pop('name')
                return JsonResponse({'success':True, 'form':form.as_ul()})

            if request_dict.get('function') == 'update_group_permissions':
                print(request_dict.get('permissions').split(','))
                model_permissions = PermissionGroup.objects.get(id=int(request_dict.get('group_id'))).model_permissions
                for model_permission_id in request_dict.get('permissions').split(','):
                    model_permissions.add(ModelPermission.objects.get(id=int(model_permission_id)))
                return JsonResponse({'success':True})

            if request_dict.get('function') == 'user_list':
                user_list = []
                users = None
                if request_dict.get('filter') is not None:
                    users = UserProfile.objects.filter(Q(username__icontains=request_dict.get('searched_username')))
                    if len(users) == 0:
                        return JsonResponse({'success':False, 'message':'Nie znalezniono profilu uzytkownika z podana nazwa'})
                if users is not None:
                    for user in users:
                        if PermissionGroup.objects.get(id=request_dict.get('group_id')) not in user.permission_group.all():
                            user_list.append({'username':user.user.username, 'user_id':user.user.id, 'profile_id':user.id})
                        else:
                            pass
                return JsonResponse({'success':True, 'users':user_list})

            if request_dict.get('function') == 'add_user_to_group':
                group = PermissionGroup.objects.get(id=request_dict.get('group_id'))
                user_profile = UserProfile.objects.get(user=User.objects.get(id=request_dict.get('user_id')))
                user_profile.permission_group.add(group)
                return JsonResponse({'success':True, 'username':user_profile.username, 'group':group.__str__()})

            if request_dict.get('function') == 'delete_permission_from_group':
                PermissionGroup.objects.get(id=request_dict.get('group_id')).model_permissions.remove(ModelPermission.objects.get(id=request_dict.get('permission_id')))
                return JsonResponse({'success':True})

            if request_dict.get('function') == 'delete_user_profile_from_group':
                UserProfile.objects.get(id=request_dict.get('user_profile_id')).permission_group.remove(PermissionGroup.objects.get(id=request_dict.get('group_id')))
                return JsonResponse({'success':True})

        else:
            return HttpResponse('bad request')

sim/templates/permissions/group_detail.html
{% extends 'permissions/permission_group.html' %}

{% block css %}
    <style>
        ul{
            list-style: none;
        }
        #id_model_permissions{
            padding: 0;
            max-height: 10vw;
            overflow: auto;
        }
        .user-row:nth-child(2n){
            background-color: #ececec;
        }
        .permission-row:nth-child(2n){
            background-color: #dadada;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="templates"></div>
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="row">
                    <div class="col-6"><h4>Nazwa grupy "{{ group.name }}"</h4></div>
                    {% if updatePermissionGroup_permission %}
                        <div class="col-1" onclick="add_permission_to_group({{ group.id }})"><i class="fas fa-plus text-success" style="font-size: 1.5vw"></i></div>
                        <div class="col-1" onclick="load_username_form()"><i class="fas fa-user-plus text-success" style="font-size: 1.5vw"></i></div>
                    {% endif %}
                    {% if deletePermissionGroup_permission %}
                        <div class="col-1"><i class="fas fa-trash-alt text-danger" style="font-size: 1.5vw"></i></div>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-6" id="permissions" style="background-color: #ececec">
                <div class="row" style=" background-color: #515151;color: white; padding-left: 1vw"><h5>Aktywne uprawnienia grupy</h5></div>
                {% for permission in model_permissions %}
                    <div class="row permission-row" data-permission_id="{{ permission.id }}">
                        <div class="col-10">{{ permission.description }}</div>
                        <div class="col-1"><i class="fas fa-trash-alt text-danger" style="cursor: pointer" data-toggle="delete_permission_from_group"></i></div>
                        <div class="col-1"><i class="far fa-edit" style="cursor: pointer"></i></div>
                    </div>
                {% endfor %}

            </div>

            <div class="col-6" id="users" style="background-color: #dadada">
                <div class="row" style=" background-color: #515151;color: white; padding-left: 1vw"><h5>Uzytkownicy</h5></div>
                {% for user in users %}
                    <div class="row user-row" data-user_profile_id="{{ user.id }}">
                        <div class="col-10">{{ user.username }}</div>
                        <div class="col-1"><i class="fas fa-trash-alt text-danger" data-toggle='delete_user_profile_from_group' style="cursor: pointer"></i></div>
                    </div>
                {% endfor %}
            </div>

        </div>

        <div class="row" id="group_manage">
            <form class="add_permission" novalidate></form>
            <div class="row">
                <div class="col-2"><small id="permission_count"></small></div>
            </div>

            <ul id="added-permissions" style="list-style: none; padding: 0;" class="col-12"></ul>
            <button class="btn" style="display: none;" onclick="update_model_permissions()" data-toggle="update_model_permissions">Save</button>
        </div>

    </div>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script>
            function add_permission_to_group(group_id) {
                $.ajax({
                    url:'{% url "group_detail_functions" %}',
                    dataType:'json',
                    method:"POST",
                    data:{'csrfmiddlewaretoken':'{{ csrf_token }}', 'group_id':group_id, 'function':'add_permission_to_group'},
                    success:function (data) {
                        $('.add_permission').append(data.form);
                    },
                    error:function(){alert('error')}
                })
            }
    </script>
{% endblock %}

{% block script_onload %}
    <script>
        $(document).ready(function () {
                Mustache.tags = ['<%', '%>'];
                $('#templates').load('/static/templates/validation_templates.html');

                //permission count controller
                $('body').on('click', ['.permission_models', '.reset-permission'], function () {
                    var itter = 0;
                    $('.permission_models:checked').each(function () {
                        itter+=1;});
                    $('#permission_count').text(itter);
                });

                //add model permission
                $('body').on('click', '.permission_models:not(#id_model_permissions)', function(){
                    $('#added-permissions li').remove();
                    var template = $('#addModelPermission').html();
                    $('.permission_models:checked').each(function () {
                        rendered_template = Mustache.render(template, {value:$(this).val(), description:$(this).parents('label').text()});
                        $('#added-permissions').prepend(rendered_template);
                    });
                });

                $('body').on('click', '.reset-permission', function () {
                    var value = $(this).parents('li').data('value');
                    $(this).parents('li').remove();
                    $('input[value="' + value + '"]').prop('checked', false);
                });

                $('body').on('click', '.permission_models:not(#id_model_permissions)', function () {
                    if( $('.permission_models:checked').length > 0 ){ $('button[data-toggle="update_model_permissions"]').show() }
                    else { $('button[data-toggle="update_model_permissions"]').hide() }
                });
        });
    </script>

    <script>
        function update_model_permissions(){
            var added_permissions = [];
            $('#added-permissions li').each(function () {
                added_permissions.push($(this).data('value'))
            });
            $.ajax({
                url:'{% url "group_detail_functions" %}',
                method:'post',
                dataType:'json',
                data:{'csrfmiddlewaretoken':'{{ csrf_token }}', 'permissions':added_permissions.join(','), 'function': 'update_group_permissions', 'group_id':'{{ group.id }}'},
                success:function (data) {
                    window.location.reload();
                },
                error:function () {
                    alert('error')
                }
            })
        }
    </script>

    <script>
        Mustache.tags = ['<%', '%>'];
        function load_username_form() {
            get_template('/static/templates/permission_templates.html', '#SearchUsernameForm', function (template) {
                $('#group_manage').append(template.html());
            })
        }

        $('body').on('keyup', '#username', function () {
            var user_name = $('#username').val();
            $.ajax({
                url:'{% url "group_detail_functions" %}',
                method:'POST',
                dataType:'json',
                data:{ 'csrfmiddlewaretoken':'{{ csrf_token }}', 'searched_username':user_name, 'filter':true, 'function':'user_list', 'group_id':'{{ group.id }}' },
                success:function (data) {
                    $('#finded_username_list').find('.one_user').remove();
                    get_template('/static/templates/permission_templates.html', '#OneUserTemplate', function (template) {
                        for(user=0; user<data.users.length; user++){
                            rendered_data = {'username':data.users[user].username, 'user_id':data.users[user].user_id};
                            rendered_template = Mustache.render(template.html(), rendered_data);
                            $('#finded_username_list').append(rendered_template);
                        }
                    });
                },
                error:function () {alert('error')}
            })
        });

        function add_to_group(user_id, group_id='{{ group.id }}') {
            $.ajax({
                url:'{% url "group_detail_functions" %}',
                method:'POST',
                dataType:'json',
                data:{"csrfmiddlewaretoken":"{{ csrf_token }}", 'user_id':user_id, 'group_id':group_id, 'function':'add_user_to_group'},
                success:function (data) {alert('Uzytkownik '+data.username+ ' zostal dodany do grupy '+data.group)},
                error:function () {alert('error')}
            })
        }
    </script>

    <script>
        function delete_permission_from_group(permission_id, group_id) {
            $.ajax({
                url:"{% url 'group_detail_functions' %}",
                method:'POST',
                dataType:'json',
                data:{'csrfmiddlewaretoken':'{{ csrf_token }}', 'permission_id':permission_id, 'group_id':group_id, 'function':'delete_permission_from_group'},
                success:function (data) {
                    remove_permission_element(permission_id);
                },
                error:function () {
                    alert('error');
                }
            })
        }

        function remove_permission_element(permission_id){
            $('.permission-row[data-permission_id="' + permission_id + '"]').slideUp(function () {$(this).remove()});
        }

        $('body').on('click', '[data-toggle="delete_permission_from_group"]', function () {
            delete_permission_from_group($(this).parents('.permission-row').data('permission_id'), {{ group.id }});
        })
    </script>

    <script>
        function delete_user_profile_from_group(user_profile_id, group_id) {
            $.ajax({
                url:'{% url "group_detail_functions" %}',
                method:'POST',
                dataType:'json',
                data:{'csrfmiddlewaretoken':'{{ csrf_token }}', 'user_profile_id':user_profile_id, 'group_id':group_id, 'function':'delete_user_profile_from_group'},
                success:function (data) {
                    remove_user_profile_element(user_profile_id);
                },
                error:function () { alert('error') }
            })
        }

        function remove_user_profile_element(user_profile_id){
            $('.user-row[data-user_profile_id="' + user_profile_id + '"]').slideUp(function () { $(this).remove() })
        }

        $('body').on('click', '[data-toggle="delete_user_profile_from_group"]', function () {
            delete_user_profile_from_group( $(this).parents('.user-row').data('user_profile_id'), {{ group.id }} )
        })
    </script>


{% endblock %}

sim/templates/permissions/permission_group.html
{% extends 'main_template.html' %}
{% load static %}

{% block css %}
    <style>
        .permission_models{
            list-style: none;
            max-height: 10vw;
            overflow: auto;
            padding: 0;
        }
    </style>
{% endblock %}

{% block js %}<script src="{% static 'js/get_template.js' %}"></script>{% endblock %}

{% block panel %}
    {% if updatePermissionGroup_permission or deletePermissionGroup_permission or createPermissionGroup_permission or viewPermissionGroup_permission %}
        <div class="sub-panel col-12" style="background-color: #a7a7a7;">
            <div class="panel-btn col-12">Istniejace uprawnienia</div>
                {% for group in activeGroups %}
                    <div class="col-12 panel-btn">
                        <div class="row">
                            <a href="#" class="col-8">{{ group.name }}</a>
                            {% if deletePermissionGroup_permission %}
                            <div class="col-1"><i class="fas fa-trash-alt text-danger" style="cursor: pointer"></i></div>
                            {% endif %}
                            {% if updatePermissionGroup_permission or createPermissionGroup_permission or deletePermissionGroup_permission %}
                                <div class="col-1" onclick="window.location.href='{% url "group_detail" group.id %}'"><i class="far fa-edit text-white" style="cursor: pointer"></i></div>
                            {% endif %}
                            {% if viewPermissionGroup_permission or createPermissionGroup_permission or updatePermissionGroup_permission or deletePermissionGroup_permission %}
                                <div class="col-1"><i class="fas fa-eye text-white" style="cursor: pointer"></i></div>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
        </div>
    {% endif %}
{% endblock %}

{% block content %}

    <div id="templates"></div>
    {% if createPermissionGroup_permission %}
        <div class="col-12" style="background-color: #f9f9f9; margin-top: 2vw">
        <!-- create permission group  -->
            <div class="row justify-content-center">
                <div class="col-12 text-center">
                    <h2>Utworzyć uprawnienie</h2>
                </div>
                <div class="col-12 col-md-12">
                    <form id="user_registration" novalidate>{% csrf_token %}
                        <div class="form-row">
                          <div class="col-12 col-md-12" data-field_name="{{ createPermissionGroupForm.name.html_name }}">
                              <div class="col-12"><label for="{{ createPermissionGroupForm.name.html_name }}">{{ createPermissionGroupForm.name.label }}</label></div>
                              <div class="col-6">{{ createPermissionGroupForm.name }}</div>
                              <div class="col-12">
                                  <div class="feedbacks"></div>
                              </div>
                          </div>
                        </div>
                        <div class="form-row">
                          <div class="col-12 col-md-12" data-field_name="{{ createPermissionGroupForm.model_permissions.html_name }}">
                              <div class="col-12"><label for="{{ createPermissionGroupForm.model_permissions.html_name }}">{{ createPermissionGroupForm.model_permissions.label }}</label></div>
                              <div class="col-12">{{ createPermissionGroupForm.model_permissions }}</div>
                              <div class="col-12">
                                  <div class="feedbacks"></div>
                              </div>
                          </div>
                        </div>
                        <div class="form-row justify-content-left">
                            <div class="col-3">
                                <button type="submit" class="btn btn-success btn-block">Dodac</button>
                            </div>
                        </div>
                    </form>
                    <div class="col-12 col-md-12">
                        <div class="row">
                            <div class="col-10">Wybrane uprawnienia</div>
                            <div class="col-2"><small id="permission_count"></small></div>
                        </div>
                        <ul id="added-permissions" style="list-style: none; padding: 0;" class="col-12"></ul>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block script_onload %}
    <script>
    Mustache.tags = ['<%', '%>'];
    $('#templates').load('/static/templates/validation_templates.html');
    $(['.invalid-feddback', '.valid-feedback']).remove();

    function remove_feedbacks(){
            $('.feedback').remove();
            $('input').removeClass(['is-valid', 'is-invalid']);
        }

    //feedbacks_list  = [{'field_name': 'field name in str', 'message': 'error message in str'}, {'field_name':'...', 'message':'...'}]
    function add_feedbacks(feedbacks_list, template){
        for (error=0; error<feedbacks_list.length; error++){
            var one_field = feedbacks_list[error];
            rendered_data = {message:one_field.message};
            rendered_template = Mustache.render(template, rendered_data);
            $('div[data-field_name="' + one_field.field_name + '"]').find('.feedbacks').append(rendered_template);
        }
    }

    $('body').on('click', 'button[type="submit"]', function (e) {
        e.preventDefault();
        remove_feedbacks();
        var name=$('#id_name').val(),
            permissions = new Array(),
            invalid_template = $('#invalidMessage').html();
        $('.permission_models:checked').each(function () {permissions.push($(this).val());});

        $.ajax({
            url:'{% url "create_permission_group" %}',
            dataType:'json',
            method:'post',
            data:{'name':name, permissions:JSON.stringify(permissions), 'csrfmiddlewaretoken':'{{ csrf_token }}'},
            success:function (data) {
                if (data.success){alert('success'); window.location.href='{% url "create_permission_group" %}';}
                else {add_feedbacks(data.errors, invalid_template)}
            },
            error:function () {alert('server error');}
        });
    });

    //permission count controller
    $('body').on('click', ['.permission_models', '.reset-permission'], function () {
        var itter = 0;
        $('.permission_models:checked').each(function () {
            itter+=1;});
        $('#permission_count').text(itter);
    });

    //add model permission
    $('body').on('click', '.permission_models:not(#id_model_permissions)', function(){
        $('#added-permissions li').remove();
        var template = $('#addModelPermission').html();
        $('.permission_models:checked').each(function () {
            rendered_template = Mustache.render(template, {value:$(this).val(), description:$(this).parents('label').text()});
            $('#added-permissions').prepend(rendered_template);
        });
    });

    $('body').on('click', '.reset-permission', function () {
        var value = $(this).parents('li').data('value');
        $(this).parents('li').remove();
        $('input[value="' + value + '"]').prop('checked', false);
    });
    </script>
{% endblock %}